apiVersion: apps/v1
kind: Deployment
metadata:
  name: cka-app
spec:
  replicas: 1
  selector:
    matchLabels:
      run: cka-app
  template:
    metadata:
      labels:
        run: cka-app
    spec:
      containers:
      - image: mshrestha/mns_cka:v4
        name: cka-app
